### ISSUE TITLE
calculator doesn't understand multiplication sign

### ISSUE THREAD

**Issue by pkar70** [microsoft/calculator#1614] opened 2021-07-21 09:58 UTC
**Describe the bug**
Calculator understand "asterisk" (U+002A) as multiplication, but it doesn't understand "multiplication" (U+00D7). Similarly, it understand "solidus" (U+002F) as a division, but doesn't understand "division" (U+00F7) nor "division slash" (U+2215). Also it doesn't understand U+2044, "fraction slash".

**Steps To Reproduce**
Open calculator, and try to enter e.g. "2×2"

**Screenshots**

**Device and Application Information**
 - OS Build: 10.0.19043.1083
 - Architecture: x86, 64 bit
 - Application Version: 10.2103.8.0
 - Region:
 - Dev Version Installed:

**Additional context**

**Requested Assignment**
 I can make PR for this, but I have no time to dig in code to find where is keyboard handled. If anyone give me hint (name of source file), I would create PR with appropriate changes.

**Comment by grochocki** [comment] 2021-07-22 07:27
Thanks for the submission! This appears to be a dupe of #1251, where this issue is discussed at length. This is not something we are looking to add at this time, but may reconsider with #526.

**Closed by grochocki** 2021-07-22 07:27 UTC
Labels: triage needed

**Comment by pkar70** [comment] 2021-07-22 08:40
I think it is not dupe of #1251 - #1251 is about regional settings, and mine is about Unicode input instead of ASCII input.
And I can make PR, but I don't know where in code is e.g. clipboard paste handling, or keyboard handling.

Clipboard paste: as in normal texts (articles for publishing etc), one have to use "×" sign for multiplication, not "*". So, when I'm writing text, I have e.g. "has area 10×15 meters, i.e." - and I cannot copy/paste "10×15" to calculator to compute it.

By the way, "programmer calculator" can be switchable between programming languages, e.g. preferred by Microsoft (not so many years ago) Visual Basic, C, etc.; and when in VB mode, use VB syntax (operators from VB, as "\", &H as hex prefix, etc.), and when in C mode, use C syntax (and 0x as hex prefix).
