### ISSUE TITLE
Why is programmer mode changed from `Alt+3` to `Alt+4` ?

### ISSUE THREAD

**Issue by yatli** [microsoft/calculator#1396] opened 2020-09-29 14:19 UTC
It was `Ctrl+3` for decades, and then `Alt+3` -- fine.
And now, without any hints, the shortcut changed to `Alt+4`. -- I'm not OK with this.
Problem is that, there's no visual hint which version I'm on, so on a random Win10 installation it'll be either `Alt+3` or `Alt+4`, depends on how happy the Windows Update is on that box.

**Comment by Chips1234** [comment] 2020-10-07 01:24
It's because the graphing calculator came on top of the programmer mode button, hence changing the order. For consistency, shortcuts should be based on the order of the buttons

**Comment by yatli** [comment] 2020-10-07 07:04
Thanks for the explanation. But I don't understand how changing the decades old mode/hotkey ordering honors consistency.

**Comment by grochocki** [comment] 2020-10-19 07:32
Thanks for the feedback, but this is a dupe of an issue that has already been resolved as by design. Please see #1011 for more details on we arrived at this decision.

**Closed by grochocki** 2020-10-19 07:32 UTC
Labels: Area: User Experience, Bug, duplicate

**Comment by patrick-compass** [comment] 2020-11-09 11:51
> It's because the graphing calculator came on top of the programmer mode button, hence changing the order. For consistency, shortcuts should be based on the order of the buttons

If you look at the code, it was very deliberately, and invasively, forced to be in that position. Adding graphing mode below Date Calculation would have been only a couple of lines of code. Putting it where it was required almost 50 lines of code that is hardly readable.

So its chosen position is completely arbitrary, it's not alphabetical or anything. If there _was_ an order it was by order of release, and now that's broken too

**Comment by patrick-compass** [comment] 2020-11-09 11:52
> Thanks for the feedback, but this is a dupe of an issue that has already been resolved as by idiotic and short-sighted design. Please see #1011 for more details on we arrived at this decision.

Fixed that for you...
