### ISSUE TITLE
The grid on Graphing is not automatically x:y=1:1

### ISSUE THREAD

**Issue by Firestar-Reimu** [microsoft/calculator#1714] opened 2021-10-08 12:29 UTC
Calculator 11.2109.8.0 on Windows 11

The grid on Graphing is not x:y=1:1, which causes perpendicular lines look like unperpendicular, etc.

![图片](https://user-images.githubusercontent.com/65082432/136558370-56fc8e5e-800e-4e61-bbc4-e2ebdda4a58d.png)

**Comment by tian-lt** [comment] 2021-10-09 01:22
Thanks for the bug report! This appears to be a dupe of #1368, so going to close for now. If I am mistaken, please let me know, and we can revisit.

**Closed as completed by tian-lt** 2021-10-09 01:22 UTC
Labels: duplicate, triage needed
