### ISSUE TITLE
Currency Convert doesn't work

### ISSUE THREAD

**Issue by hellblazer91** [microsoft/calculator#1796] opened 2022-02-14 16:08 UTC
![image](https://user-images.githubusercontent.com/55159507/153901044-f7bad695-b982-4b95-9282-60e5f3b74526.png)

**Comment by grochocki** [comment] 2022-02-15 07:22
Thanks for the bug report! This appears to be a dupe of #1789, so resolving this to focus discussion there.

**Closed by grochocki** 2022-02-15 07:22 UTC
Labels: triage needed
