### ISSUE TITLE
Keep value between mode change

### ISSUE THREAD

**Issue by twoco** [microsoft/calculator#1997] opened 2023-05-01 10:16 UTC
Switching between modes (standard, scientific, programmer, ...) resets the value to 0. It's annoying if you started the calculation and see you are on the wrong calc type.

We could just transport that value from one type to another. Like copy (CTRL + C), then change calc type and paste (CTRL + V). Maybe the value is not compatible or just don't work. Therefore this is just a try to use the value. Set zero on error.

**Comment by mcooley** [comment] 2023-05-11 18:52
This suggestion is a duplicate of #1807. The idea can be discussed further in that issue. Thanks!

**Closed** 2023-05-11 19:30 UTC
Labels: Enhancement
