### ISSUE TITLE
How to remove fucking spaces from this calculator or return to windows 7 verison.

### ISSUE THREAD

**Issue by UnrealKaraulov** [microsoft/calculator#2134] opened 2024-03-15 13:03 UTC
How to remove fucking spaces from this calculator or return to windows 7 verison.

![image](https://github.com/microsoft/calculator/assets/88730285/ad08c918-9766-488c-8483-e0a1267090f6)

And after copy result same fucking spaces in output text!

![image](https://github.com/microsoft/calculator/assets/88730285/1a337793-b930-40d9-ae79-40bc6c5cd60f)

OS : Windows 11 x64
```[tasklist]
### Tasks
- [x] https://github.com/microsoft/calculator/issues/2135
```

**Comment by grochocki** [comment] 2024-03-15 23:49
Closing as dupe of #1331

**Closed by grochocki** 2024-03-15 23:49 UTC
Labels: duplicate

**Comment by karakakarkarkar** [comment] 2024-03-16 07:48
@grochocki why closed as completed if this fucking spaces not removed from calculator
